### ISSUE TITLE
term search result ordering is inconsistent depending on limit

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#122]
Querying term search with "fin" and `limit=2` yields the following result, with the exact match returned first:
```
curl -X GET "https://kb.phenoscape.org/api/term/search?text=fin&type=http%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23Class&properties=%5B%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%22%2C%20%22http%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23hasExactSynonym%22%2C%20%22http%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23NarrowSynonym%22%2C%20%22http%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23hasBroadSynonym%22%5D&includeDeprecated=false&limit=2" -H "accept: application/json"
``` 
```js
{
  "results": [
    {
      "@id": "http://purl.obolibrary.org/obo/UBERON_0008897",
      "label": "fin",
      "isDefinedBy": "http://purl.obolibrary.org/obo/uberon.owl",
      "matchType": "exact"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/UBERON_0002389",
      "label": "manual digit",
      "isDefinedBy": "http://purl.obolibrary.org/obo/uberon.owl",
      "matchType": "broad"
    }
  ]
}
```
If limit is reduced to 1 (if I only want the exact match, that's all I should need), then a "broad" match is first (and now only):
```js
{
  "results": [
    {
      "@id": "http://purl.obolibrary.org/obo/UBERON_0002389",
      "label": "manual digit",
      "isDefinedBy": "http://purl.obolibrary.org/obo/uberon.owl",
      "matchType": "broad"
    }
  ]
}
```
And if conversely the limit is increased to 6, I also start seeing some partial matches:
```js
{
  "results": [
    {
      "@id": "http://purl.obolibrary.org/obo/UBERON_0008897",
      "label": "fin",
      "isDefinedBy": "http://purl.obolibrary.org/obo/uberon.owl",
      "matchType": "exact"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/ZFA_0000108",
      "label": "fin (zebrafish)",
      "isDefinedBy": "http://purl.obolibrary.org/obo/zfa.owl",
      "matchType": "partial"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/UBERON_2005316",
      "label": "fin fold pectoral fin bud",
      "isDefinedBy": "http://purl.obolibrary.org/obo/uberon.owl",
      "matchType": "partial"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/UBERON_0009552",
      "label": "distal segment of manual digit",
      "isDefinedBy": "http://purl.obolibrary.org/obo/uberon.owl",
      "matchType": "broad"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/UBERON_0002389",
      "label": "manual digit",
      "isDefinedBy": "http://purl.obolibrary.org/obo/uberon.owl",
      "matchType": "broad"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/UBERON_0009565",
      "label": "nail of manual digit",
      "isDefinedBy": "http://purl.obolibrary.org/obo/uberon.owl",
      "matchType": "broad"
    }
  ]
}
```

This inconsistency means that it's quite unpredictable for the client how to set a low limit while not losing matches that are better than the ones still returned.

**Comment by balhoff** [comment]
This problem seems to be a little tricky; thanks for digging into it. Here are more details for the query results for "fin" with limit=2:

```
phenoscape-kb-services ( ?rank = "2"^^xsd:int ) ( ?term = <http://purl.obolibrary.org/obo/UBERON_0002389> ) ( ?matched_label = "finger" ) ( ?relevance = "1.0"^^xsd:double ) ( ?term_label = "manual digit" ) ( ?ont = <http://purl.obolibrary.org/obo/uberon.owl> )
phenoscape-kb-services ( ?rank = "3"^^xsd:int ) ( ?term = <http://purl.obolibrary.org/obo/UBERON_0008897> ) ( ?matched_label = "fin" ) ( ?relevance = "1.0"^^xsd:double ) ( ?term_label = "fin" ) ( ?ont = <http://purl.obolibrary.org/obo/uberon.owl> )
```

The full-text search is giving a match to "finger" a better rank than a match to "fin" (I don't know why there is nothing with rank=1). This service does not do a separate query for an exact label match to prioritize that if it exists; I suppose we could do that. Otherwise I can try to figure out if there are some Lucene parameters to tweak that would give a high score to an exact match.

An alternative service which requires an exact match to `rdfs:label` would be `/term/resolve_label_expression`.

**Comment by hlapp** [comment]
I think the particular problem here is that the ordering is inconsistent between different values of limit. It is _not_ inconsistent for repeated invocations with the same value of limit.So what causes the ordering to differ for different values of limit.

Can you explain how limit works because I think that's at the root of the problem.

**Comment by balhoff** [comment]
It looks confusing because the results are reordered after they are formatted. They are initially output by a SPARQL query which is ordered and limited by `?rank`. I now have a solution for always getting an exact match first, if it exists. I will continue thinking about it though to see if the ordering inconsistency can go away.

**Comment by balhoff** [comment]
To expand on the ordering issue, the query engine considers "finger" (an exact synonym of 'manual digit') a better match than "fin (zebrafish)", so it comes out first. But then I take all the results and put the ones that contain the search text within their `rdfs:label` at the front of the results.

**Comment by balhoff** [comment]
I've updated the service so that exact matches always have the highest match score (prior to query limiting). However if you are searching other property values besides `rdfs:label`, the post-query reordering can still be somewhat confusing as you describe above, because `rdfs:label` values are always returned in the results, and they impact the ordering.

We could discuss this at a dev meeting.

**Comment by balhoff** [comment]
This service continues to be problematic. Changing the result limit from 9 to 10 to 20 to 30 returns unexpected result counts.

```
curl -X GET "https://kb.phenoscape.org/api/term/search?text=fin&type=http%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23Class&properties=%5B%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%22%2C%20%22http%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23hasExactSynonym%22%2C%20%22http%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23NarrowSynonym%22%2C%20%22http%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23hasBroadSynonym%22%5D&definedBy=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fuberon.owl&includeDeprecated=false&limit=30" -H "accept: application/json"
```
