### ISSUE TITLE
/term/label returns a result even for IRIs not in the database

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-services#145]
For example:
```sh
curl -X GET "https://kb.phenoscape.org/api/term/label?iri=http%3A%2F%2Ffoobar.com%2Fbaz" -H "accept: application/json"
```
yields
```js
{
  "@id": "http://foobar.com/baz",
  "label": "http://foobar.com/baz"
}
```
Any made up input will produce a result, with `label` set to the input.

Obviously, assuming that terms with the same label as their IRI don't exist (in the KB), this should be detectable by testing whether `@id` and `label` have equal values. But shouldn't there just be an empty result if the IRI can't be found?

(And BTW is there a reason this return value doesn't have the `{"result" = [{}, ...]}` structure?)

**Comment by balhoff** [comment]
This endpoint generates some labels based on the expression embedded in the URI. This was from back before we generated these labels and stored them in the database. I am trying to get away from doing this. Having you use the API is really turning up some weird corners.

It isn't structured as `{"result" = [{}, ...]}` because it doesn't return a list. That structure originated from some APIs in AngularJS 1.x which worked much better with objects with at least one property rather than root-level JSON arrays.

**Comment by balhoff** [comment]
This now returns `null` if a label is not found.
