### ISSUE TITLE
taxon phenotype annotations returns only TSV when more than 1000 records are requested

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-services#154]
This is a reminder to figure out how to handle content negotiation when using streaming responses.

**Comment by hlapp** [comment]
Is there a chance this can get fixed soon? It refuses to accept `application/json` even if the limit parameter is set to higher than 1000, whether there are that results or not.

**Comment by balhoff** [comment]
Yes, will try to figure this out soon. You are looking at the same endpoint.

**Comment by hlapp** [comment]
@balhoff I think this got closed automatically, and deployment is still pending, right?

**Comment by balhoff** [comment]
Deployed now (one handed)!

**Comment by hlapp** [comment]
Looks like now we don't have `Content-length` header anymore in the response. I'm going to assume that this is necessarily so due to how it's streamed, rather than a mistake somewhere, i.e., the server really can't know anymore what the content length is going to be. I think I can change the Rphenoscape code to deal with this, but the necessary downside is that the client cannot detect if a response is incomplete when the connection closes (which may be due to timeout).
