### ISSUE TITLE
API to resolve a given pair of gene name and taxon name

### ISSUE THREAD

**Issue by xu-hong** [phenoscape/phenoscape-kb-services#27]
Gene IRI is used as an argument in several Phenoscape Knowledge APIs (e.g. Semantic similarity query) so I think an API to resolve a text input to a gene IRI would be necessary for applications that allow texts as inputs.

In the case of resolving a gene name, a corresponding taxon name is also required. And similar to Ontology class search API, this API should take gene name and taxon name as text inputs and return a list of pairs of the IRI and the label.

**Comment by balhoff** [comment]
Here is a service that exists (I am still slowly documenting these things): http://docs.phenoscapekb.apiary.io/#reference/genes/gene-search/search-for-genes-by-gene-symbol

It allows search by gene symbol, but not by taxon. The taxon for each result is returned, so you can filter client side, but I can add a taxon parameter as well.

**Comment by hlapp** [comment]
> Here is a service that exists (I am still slowly documenting these things): http://docs.phenoscapekb.apiary.io/#reference/genes/gene-search/search-for-genes-by-gene-symbol
> 
> It allows search by gene symbol, but not by taxon. The taxon for each result is returned, so you can filter client side, but I can add a taxon parameter as well.

Two things I find missing:

1. Does this allow wildcards in the query string, and does it ignore capitalization or not? Perhaps one should be able to turn off ignoring capitalization, if that's the default, so that exact matches (which often include capitalization to differentiate between taxa) are possible.
2. The latin binomial doesn't seem to be the returned results. If it were, client-side filtering should have most or everything that it needs.

**Comment by balhoff** [comment]
I've added an option for passing a taxon IRI. The list of valid model organism taxa is in the Apiary docs. Also, I added the Latin binomial as the taxon label.

The query string has an automatic wildcard at the end; prefix matches are always returned. Personally I think adding further options like matching capitalization is going too far, especially since you can now specify the taxon.
