### ISSUE TITLE
API to return all ancestors/descendants for a given term

### ISSUE THREAD

**Issue by xu-hong** [phenoscape/phenoscape-kb-services#30]
As is raised in #14, an API to return all ancestors for a given term would be a computationally cheaper way to determine whether one term or any term among a list of terms is the ancestor of a given term. 

Similarly, an API to return all descendants for a given term is needed to determine whether one term or a list of terms is the descendant of it.

**Comment by balhoff** [comment]
I have added two new services, "all ancestors" and "all descendants". Documentation is on Apiary: http://docs.phenoscapekb.apiary.io/#reference/terms/ancestors

Let me know if these work or if you would like some additional filtering options. Thanks!

**Comment by hlapp** [comment]
How much trouble and/or possible performance penalty would it be to broaden the input parameter (which I understand is term IRI right now) to a class expression (which could obviously also be a term IRI)?

**Comment by balhoff** [comment]
Not much trouble. The possible performance penalty is that I would change from using a SPARQL path query to using a DL query to Owlery. For one query the performance is good. But due to Elk limitations, Owlery responses can only answer one query at a time, so a query can block. This would really just be shadowing an API that already exists for Owlery:

http://docs.owlery.apiary.io/#reference/dl-queries/superclasses/get-superclasses-of-a-named-class-or-expression

**Comment by hlapp** [comment]
So let's leave it as is then. We really have no control over how many people run rphenoscape code at any given time.
