### ISSUE TITLE
Some services are not ignoring limit=0

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-services#64]
Services are meant to return all results if `limit=0`. When some services were migrated to new-style SPARQL templates, this was missed.

**Comment by johnbradley** [comment]
I tried to use `limit=0` with the [/term/search endpoint](https://kb.phenoscape.org/apidocs/#/Terms/get_term_search) and it does not return all results. It returns an empty array instead. In my testing I entered "fin" for the required `text` parameter which has over 100 results. Has this bug resurfaced for some endpoints or is there another way to retrieve all the results?

**Comment by hlapp** [comment]
It seems to be working correctly (i.e., not putting a limit?) if the `limit` parameter is left off (i.e., left empty in the "Try it out" interface).

That said, the documentation does not say what happens if the `limit` parameter is left off, so we don't know whether indeed there is no limit, or whether the number of results returned is less than or capped at the internal default limit.

**Comment by johnbradley** [comment]
@hlapp In my testing it defaults to only returning 100 items if the `limit` parameter is left empty even though there are more than 100 items available for "fin".

**Comment by hlapp** [comment]
Looks like a bug to me. @balhoff ?

**Comment by balhoff** [comment]
It is a bug. The default is `100`: https://github.com/phenoscape/phenoscape-kb-services/blob/c1b1c5a49d61232dddc0adc0c8ae9b54e6f3f6fd/src/main/scala/org/phenoscape/kb/Main.scala#L149

We are missing a check for `0` here: https://github.com/phenoscape/phenoscape-kb-services/blob/c1b1c5a49d61232dddc0adc0c8ae9b54e6f3f6fd/src/main/scala/org/phenoscape/kb/Term.scala#L426-L466
